create table user (
  id int unsigned primary key auto_increment not null,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email varchar(255) not null unique,
  password varchar(255) not null,
  subscription BOOLEAN NOT NULL,
  role VARCHAR(50) NOT NULL
);

create table movie (
  id int unsigned primary key auto_increment not null,
  title varchar(255) not null,
  synopsis TEXT not null,
  release_year YEAR  not null,
  duration TIME not null,
  poster VARCHAR(255) NOT NULL,
  trailer VARCHAR(255) NOT NULL,
  casting TEXT NOT NULL,
  production TEXT NOT NULL
);

create table genre (
id int unsigned primary key auto_increment not null,
name VARCHAR(255) not null
);

create table movie_genre (
movie_id INT NOT NULL,
genre_id INT NOT NULL
);

create table watchlist (
movie_id int not null,
user_id int not null
);

insert into movie (title, synopsis, release_year, duration, poster, trailer, casting, production)
VALUES
  ("Matrix","Programmeur anonyme dans un service administratif le jour, Thomas Anderson devient Neo la nuit venue. Sous ce pseudonyme, il est l'un des pirates les plus recherchés du cyber-espace. A cheval entre deux mondes, Neo est assailli par d'étranges songes et des messages cryptés provenant d'un certain Morpheus. Celui-ci l'exhorte à aller au-delà des apparences et à trouver la réponse à la question qui hante constamment ses pensées : qu'est-ce que la Matrice ? Nul ne le sait, et aucun homme n'est encore parvenu à en percer les defenses. Mais Morpheus est persuadé que Neo est l'Elu, le libérateur mythique de l'humanité annoncé selon la prophétie. Ensemble, ils se lancent dans une lutte sans retour contre la Matrice et ses terribles agents...", "1999", "02:15:00",  "https://fr.web.img4.acsta.net/c_310_420/medias/04/34/49/043449_af.jpg", "https://www.youtube.com/watch?v=vKQi3bBA1y8&ab_channel=RottenTomatoesClassicTrailers", "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving", "Lilly Wachowski et Lana Wachowski"),
  ("Inception","Un voleur spécialisé dans l'extraction d'informations secrètes par le biais du partage de rêves se voit confier l'impossible mission d'implanter une idée dans l'esprit d'un dirigeant...", "2010", "2:28:00","https://images.affiches-et-posters.com//albums/3/4532/medium/4532-affiche-film-inception-cast.jpg", "https://www.youtube.com/watch?v=YoHD9XEInc0", "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy", "Warner Bros. Pictures, Legendary Pictures, Syncopy"),
  ("The Godfather", "Le patriarche vieillissant d'une puissante famille mafieuse transfère le contrôle de son empire clandestin à son fils réticent, déclenchant une série de trahisons et de conflits familiaux...", "1972", "2:55:00", "https://i.ebayimg.com/images/g/kWQAAOSwArteJsIw/s-l1200.jpg", "https://www.youtube.com/watch?v=sY1S34973zA", "Marlon Brando, Al Pacino, James Caan", "Paramount Pictures"),
  ("The Shawshank Redemption", "Condamné à la prison à vie, un banquier entretient une amitié inattendue qui l'aide à trouver la rédemption et l'espoir derrière les barreaux...", "1994", "2:22:00", "https://images.squarespace-cdn.com/content/v1/657716dc6cd59d329f8cc943/1702303456952-89SVMRXKDUZ65S4279HJ/TSRL+Poster.jpg", "https://www.youtube.com/watch?v=6hB3S9bIaco", "Tim Robbins, Morgan Freeman", "Castle Rock Entertainment"),
  ("The Dark Knight", "Batman doit affronter le Joker, un criminel sadique qui transforme Gotham en un terrain de chaos, mettant à l'épreuve ses idéaux et sa détermination...", "2008", "2:32:00", "https://fr.web.img2.acsta.net/medias/nmedia/18/63/97/89/18949761.jpg", "https://www.youtube.com/watch?v=EXeTwQWrcwY", "Christian Bale, Heath Ledger, Aaron Eckhart", "Warner Bros. Pictures"),
  ("Fight Club", "Un employé de bureau insatisfait et un vendeur de savon forment un club secret de combat, qui dégénère en une organisation anarchique aux conséquences imprévues...", "1999", "2:19:00", "https://fr.web.img6.acsta.net/r_1280_720/pictures/210/212/21021246_20130719135446815.jpg", "https://www.youtube.com/watch?v=SUXWAEX2jlg", "Brad Pitt, Edward Norton, Helena Bonham Carter", "20th Century Fox, Regency Enterprises"),
  ("Nomadland", "Une femme qui a tout perdu se lance dans un voyage à travers l'Ouest américain, adoptant le mode de vie d'une nomade moderne...", "2020", "1:47:00", "https://www.wiztopic.com/file/fx648pt7qg-phpnxojjt", "https://www.youtube.com/watch?v=6sxCFZ8_d84", "Frances McDormand, David Strathairn", "Searchlight Pictures"),
  ("Dune", "Dans un futur lointain, la lutte pour le contrôle d'une planète riche en ressources mène à des conflits interstellaires et politiques...", "2021", "2:35:00", "https://m.media-amazon.com/images/I/71XlZvKMwoL.jpg", "https://www.youtube.com/watch?v=n9xhJrPXop4", "Timothée Chalamet, Rebecca Ferguson, Oscar Isaac", "Warner Bros. Pictures, Legendary Entertainment, Villeneuve Films"),
  ("The Power of the Dog", "Dans le Montana des années 1920, un charismatique rancher cache des secrets sombres qui vont perturber l'équilibre d'une famille...", "2021", "2:06:00", "https://media.senscritique.com/media/000020786307/0/the_power_of_the_dog.jpg", "https://www.youtube.com/watch?v=UpRzGl792tk", "Benedict Cumberbatch, Kirsten Dunst, Jesse Plemons", "Fox Searchlight Pictures"),
  ("Everything Everywhere All at Once", "Une femme ordinaire se retrouve plongée dans une aventure interdimensionnelle pour sauver le multivers, confrontée à d'innombrables versions d'elle-même...", "2022", "139", "https://media.senscritique.com/media/000021157918/0/everything_everywhere_all_at_once.png", "https://youtu.be/wxN1T1uxQ2g", "Michelle Yeoh, Ke Huy Quan, Stephanie Hsu", "A24"),
  ("Drive My Car", "Suite à la perte de sa femme, un acteur se lance dans un voyage introspectif en acceptant un rôle dans une production théâtrale singulière...", "2021", "2:59:00", "https://fr.web.img5.acsta.net/pictures/21/08/04/12/37/4421523.jpg", "https://youtu.be/6BPKPb_RTwI", "Hidetoshi Nishijima, Reika Kirishima", "ROK International"),
  ("L'amour au présent", "Une histoire touchante qui explore les paradoxes de l'amour moderne dans un monde en perpétuel changement...", "2025", "1:45:00", "https://media.senscritique.com/media/000022450747/300/lamour_au_present.png", "https://youtu.be/9yadSQmKU_s", "Julien Dupont, Sophie Martin", "Cinema France"),
  ("Un ours dans le Jura", "Un ours solitaire traverse le Jura pour découvrir le sens de la vie et l'amitié inattendue...", "2025", "1:50:00", "https://media.senscritique.com/media/000022468759/300/un_ours_dans_le_jura.png", "https://youtu.be/zfQfUoN6IwM", "Marc Leblanc, Camille Roche", "Jura Films"),
  ("Bird", "Un voyage émouvant dans l'univers d'un oiseau légendaire, symbole de liberté...", "2025", "2:00:00", "https://media.senscritique.com/media/000022481993/300/bird.png", "https://youtu.be/scMh3X6byns", "Emma Thompson, Robert Redford", "Skyline Studios"),
  ("Elevation", "Un thriller haletant qui emmène les spectateurs au sommet de la tension et du suspense...", "2025", "2:05:00", "https://media.senscritique.com/media/000022548839/300/elevation.jpg", "https://youtu.be/kt0V2rpEouE", "Alice Durand, Maxime Leroy", "High Altitude Pictures"),
  ("Wallace et Gromit- La Palme de la Vengeance", "Les célèbres inventeurs se retrouvent au cœur d'une aventure rocambolesque mêlant humour et suspense...", "2025", "1:40:00", "https://media.senscritique.com/media/000022468409/300/wallace_et_gromit_la_palme_de_la_vengeance.png", "https://youtu.be/pUaJVSWPtZk", "Voix : Nicolas Durand, Claire Fournier", "Stop Motion Productions"),
  ("La Chambre d'à côté", "Une comédie dramatique où les secrets d'une chambre voisine bouleversent la vie de ses habitants...", "2025", "1:55:00", "https://media.senscritique.com/media/000022497713/300/la_chambre_d_a_cote.png", "https://youtu.be/41YRoaUsf6U", "Isabelle Moreau, Jean-Paul Gaultier", "Ciné Lumière"),
  ("Criminal Squad Pantera", "Une unité d'élite se bat contre le crime dans une ville aussi féroce qu'une panthère...", "2025", "2:10:00", "https://media.senscritique.com/media/000022545552/300/criminal_squad_pantera.png", "https://youtu.be/K-IUU8VVKvM", "Thomas Bernard, Lara Dupuis", "Action Movies Inc."),
  ("Mémoires d'un escargot", "À la mort de son père, la vie heureuse et marginale de Grace Pudel, collectionneuse d'escargots et passionnée de lecture, vole en éclats. Arrachée à son frère jumeau Gilbert, elle atterrit dans une famille d'accueil à l'autre bout de l’Australie. Suspendue aux lettres de son frère, ignorée par ses tuteurs et harcelée par ses camarades de classe, Grace s’enfonce dans le désespoir. Jusqu’à la rencontre salvatrice avec Pinky, une octogénaire excentrique qui va lui apprendre à aimer la vie et à sortir de sa coquille…", "2025", "1:34:00", "https://media.senscritique.com/media/000022500290/300/memoires_dun_escargot.png", "https://youtu.be/GHlI58s-23w", "Gilbert Pudel (voice): Kodi Smit-McPhee, Pinky (voice): Jacki Weaver, James The Magistrate (voice): Eric Bana, Percy (voix): Dominique Pinon, Ruth (voix): Magda Szubanski, Bill Clarke (voice): Nick Cave, Denise Floyd (voice): Adam Elliot, Additional (voice): Flynn Wandin, Additional (voice): Ruby Davis", "Wild Bunch Distribution"),
  ("Spectateurs !", "Un regard acerbe sur la société moderne où les observateurs deviennent acteurs d'une réalité déconcertante...", "2025", "1:55:00", "https://media.senscritique.com/media/000022109324/300/spectateurs.png", "https://youtu.be/k0Ds2Udv-7A", "Luc Durand, Elise Martin", "Reflet Productions"),
  ("Wolf Man", "Une réinvention moderne du mythe du loup-garou, mêlant horreur et drame psychologique...", "2025", "2:00:00", "https://media.senscritique.com/media/000022567984/300/wolf_man.png", "https://youtu.be/XVyodxcVUxo", "Vincent Cassel, Marion Cotillard", "Dark Moon Studios"),
  ("Babygirl", "Un portrait touchant d'une jeune femme confrontée aux défis de la vie et de l'identité...", "2025", "1:40:00", "https://media.senscritique.com/media/000022574299/300/babygirl.png", "https://youtu.be/jaX7rlzeM44", "Lola Dubois, Antoine Mercier", "HeartBeat Films"),
  ("Je suis toujours là", "Un drame introspectif sur la résilience et la persévérance face aux épreuves de la vie...", "2025", "1:50:00", "https://media.senscritique.com/media/000022526927/300/je_suis_toujours_la.jpg", "https://youtu.be/65UDWfkJGdo", "Claire Simon, Laurent Pascal", "Everlasting Pictures"),
  ("In the Grey", "Un thriller mystérieux où la frontière entre bien et mal se dissout dans une zone grise...", "2025", "2:05:00", "https://www.ecranlarge.com/content/uploads/2024/11/in-the-grey-affiche-officielle-630x945.jpg", "https://youtu.be/zBqavRXa-7M", "Eva Green, Michael Fassbender", "Grey Area Films"),
  ("Back in Action", "Alors qu’ils ont démissionné depuis longtemps de la CIA pour fonder une famille, Emily et Matt sont rattrapés malgré eux par l’espionnage lorsque leur couverture est démasquée...", "2025", "2:15:00", "https://media.senscritique.com/media/000022469847/300/back_in_action.png", "https://youtu.be/zXTBl_31SXY", "Jamie Foxx, Cameron Diaz", "Seth Gordon"),
  ("Pinocchio Unstrung", "Une réinterprétation audacieuse du conte classique, où le bois prend vie dans une aventure inattendue...", "2025", "1:45:00", "https://media.senscritique.com/media/000022323112/300/pinocchio_unstrung.jpg", "https://youtu.be/arQv2zWpgiY", "Ewan McGregor, Scarlett Johansson", "Fairy Tale Productions"),
  ("Better Man", "Une quête de rédemption et de transformation dans un monde en quête de justice et d'égalité...", "2025", "1:55:00", "https://media.senscritique.com/media/000022599251/300/better_man.png", "https://youtu.be/o7kB9SjkIIk", "Chris Hemsworth, Emily Blunt", "Evolution Films"),
  ("Joues avec le feu", "Un drame palpitant où la passion met le feu aux relations et dévoile des secrets inavoués...", "2025", "2:00:00", "https://media.senscritique.com/media/000022511252/300/jouer_avec_le_feu.png", "https://youtu.be/SjDGx7ASUbg", "Sophie Marceau, Vincent Cassel", "Firelight Productions"),
  ("Vol à haut risque", "L'US Marshals Madelyn Harris est chargée d'escorter Winston, criminel et informateur, qui va témoigner contre un parrain de la mafia. Pendant leur voyage en avion, elle se méfie rapidement du pilote, Daryl Booth, qui ne semble pas être l'homme qu'il prétend...", "2025", "1:50:00", "https://media.senscritique.com/media/000022582019/300/vol_a_haut_risque.jpg", "https://youtu.be/VG6iWe_8SHc", "Mark Wahlberg, Michelle Dockery, Topher Grace, Leah Remini, Paul Ben-Victor", "Mel Gibson"),
  ("Nightbitch", "Après la naissance de son fils, une ancienne artiste reste chez elle et commence à développer la peur de se transformer en chien...", "2025", "1:38:00", "https://media.senscritique.com/media/000022545859/300/nightbitch.png", "https://youtu.be/KlhgQRGGHk0", "Amy Adams, Scoot McNairy", "Marielle Heller"),
  ("Star Trek: Section 31", "L'impératrice Philippa Georgiou rejoint une division secrète de Starfleet chargée de protéger la Fédération des planètes unies....", "2025", "1:50:00", "https://media.senscritique.com/media/000022592051/300/star_trek_section_31.jpg", "https://youtu.be/kYfXhCp2UVY", "Michelle Yeoh, Omari Hardwick, Sam Richardson, Robert Kazinsky, Kacey Rohl", "Olatunde Osunsanmi"),
  ("Un parfait inconnu", "New York, début des années 60. Au cœur de l’effervescente scène musicale et culturelle de l’époque, un énigmatique jeune homme de 19 ans arrive dans le West Village depuis son Minnesota natal, avec sa guitare et un talent hors normes qui changeront à jamais le cours de la musique américaine. Alors qu’il noue d’intimes relations durant son ascension vers la gloire, il finit par se sentir étouffé par le mouvement folk et, refusant d’être mis dans une case, fait un choix controversé qui aura des...", "2025", "2:21:00", "https://media.senscritique.com/media/000022600281/300/un_parfait_inconnu.png", "https://youtu.be/BPSw48CJamE", "Thimothée Chalamet, Bob Dylan, Edward Norton, Elle Fanning, Monica Barbaro, Boyd Holbrook", "James Mangold"),
  ("Companion", "Après avoir été invitée à un week-end dans la propriété au bord du lac de son nouvel amoureux, Iris découvre un terrible secret...", "2025", "1:37:00", "https://media.senscritique.com/media/000022544367/300/companion.jpg", "https://youtu.be/7K6B4R9Ce0M", "Sophie Thatcher, Jack Quaid, Rupert Friend, Lukas Gage, Harvey Guillen, Marc Menchaca", "Greg Kwedar "),
  ("Sing Sing", "Incarcéré à la prison de Sing Sing pour un crime qu’il n’a pas commis, Divine G se consacre corps et âme à l’atelier théâtre réservé aux détenus. À la surprise générale, l’un des caïds du pénitencier, Divine Eye se présente aux auditions...", "2025", "1:45:00", "https://media.senscritique.com/media/000022339180/300/sing_sing.png", "https://youtu.be/2zjXCo-Nzt4", "Colman Domingo, Clarence Maclin, Sean Dino Johnson, Paul Raci, Sean San Jose, Miguel Valentin", "Redemption Studios"),
  ("God Save the Tuche", "Les Tuche mènent à nouveau une vie paisible à Bouzolles. Mais lorsque le petit-fils de Jeff et Cathy est sélectionné pour un stage de football à Londres, c’est l’occasion rêvée pour toute la famille d’aller découvrir l’Angleterre et de rencontrer la famille royale. Entre chocs culturels et maladresses, les Tuche se retrouvent plongés au cœur de la royauté anglaise, qui n’est pas prête d’oublier leur séjour!", "2025", "1:33:00", "https://media.senscritique.com/media/000022525173/300/god_save_the_tuche.png", "https://youtu.be/K3aUaFbrd8g", " Jean-Paul Rouve, Isabelle Nanty, Claire Nadeau, Sarah Stern, Pierre Lottin, Theo Fernandez", "Jean-Paul Rouve"),
  ("Presence", "Une famille emménage dans une nouvelle maison, hantée par une mystérieuse présence....", "2025", "1:25:00", "https://media.senscritique.com/media/000022592413/300/presence.png", "https://youtu.be/4OBKT5yMTU0", "Lucy Liu, Julia Fox, Chris Sullivan, Lucas Papaelias", "Steven Soderbergh"),
  ("Paddington au Pérou", "Alors que Paddington rend visite à sa tante Lucy bien-aimée, qui réside désormais à la Maison des ours retraités au Pérou, la famille Brown et notre ours préféré plongent dans un voyage inattendu et plein de mystères, à travers la forêt amazonienne et jusqu'aux sommets des montagnes du Machu Picchu...", "2025", "1:43:00", "https://media.senscritique.com/media/000022635036/300/paddington_au_perou.png", "https://youtu.be/Fp-1L1KOIk8", "Ben Whishaw, Guillaume Gallienne, Hugh Bonneville, Emily Mortimer, Olivia Colman, Antonio Banderas", "Antoine Chevrollier"),
  ("La Pampa", "Willy et Jojo, deux ados inséparables, passent leur temps à chasser l’ennui dans un petit village au cœur de la France. Ils se sont fait une promesse : ils partiront bientôt pour la ville. Mais Jojo cache un secret. Et quand tout le village le découvre, les rêves et les familles des deux amis volent en éclat...", "2025", "1:44:00", "https://media.senscritique.com/media/000022602859/300/la_pampa.png", "https://youtu.be/jZCpZAGCsoY", "Sayyid El Alami, Amaury Foucher, Damien Bonnard, Florence Janas, Victor Artus Solaro (Artus), Léonie Dahan-Lamort", "Pablo Larraín"),
  ("Maria", "La vie de la plus grande chanteuse d’opéra du monde, Maria Callas, lors de ses derniers jours, en 1977, à Paris...", "2025", "2:04:00", "https://media.senscritique.com/media/000022484202/300/maria.png", "https://youtu.be/1z0kHDNA4bU", "Angelina Jolie, Pierfrancesco Favino, Alba Rohrwacher, Haluk Bilginer, Kodi Smit-McPhee, Stephen Ashfield", "Pablo Larraín"),
  ("The Order - la confrérie de l'ombre", "Terry Husk, un agent chevronné du FBI, découvre un complot terroriste à l'intérieur du pays visant à renverser le gouvernement fédéral....", "2025", "1:54:00", "https://media.senscritique.com/media/000022635006/300/the_order_la_confrerie_de_l_ombre.png", "https://youtu.be/_muGqDpJRQM", "Jude Law, Nicholas Hoult, Tye Sheridan, Jurnee Smollett, Odessa Young, Alison Oliver", "Justin Kurzel"),
  ("The Brutalist", "L'histoire, sur près de trente ans, d'un architecte juif né en Hongrie, László Toth. Revenu d'un camp de concentration, il émigre avec sa femme, Erzsébet, après la fin de la Seconde Guerre mondiale aux États-Unis pour connaître son rêve américain...", "2025", "3:35:00", "https://media.senscritique.com/media/000022647875/300/the_brutalist.png", "https://youtu.be/oFGs3-R1NyU", "Adrien Brody, Felicity Jones, Guy Pearce, Joe Alwyn, Raffey Cassidy, Stacy Martin", "Brady Corbet"),
  ("Les Damnés", "Hiver 1862. Pendant la guerre de Sécession, l’armée des Etats-Unis envoie à l’Ouest une compagnie de volontaires pour effectuer une patrouille dans des régions inexplorées. Alors que leur mission change de cap, ils questionnent le sens de leur engagement...", "2025", "1:28:00", "https://media.senscritique.com/media/000022544327/300/les_damnes.jpg", "https://youtu.be/GCjP6gj9oeA", "Cuyler Ballenger, Jeremiah Knupp, René W. Solomon, Noah Carlson, Timothy Carlson", "Roberto Minervini"),
  ("Captain America: Brave New World", "Peu après avoir fait la connaissance du nouveau président des Etats-Unis Thaddeus Ross, Sam Wilson se retrouve plongé au coeur d'un gigantesque incident international. Dans une lutte acharnée contre la montre, il se retrouve contraint de découvrir la raison de cet infâme complot avant que le véritable cerveau de l’opération ne mette bientôt le monde entier à feu et à sang...", "2025", "1:58:00", "https://media.senscritique.com/media/000022442264/300/captain_america_brave_new_world.png", "https://youtu.be/PFU4wlAg7l0", "Anthony Mackie, Harrison Ford, Danny Ramirez, Shira Haas, Tim Blake Nelson, Carl Lumbly", "Marvel Studios"),
  ("Bridget Jones - Folle de lui", "Bridget Jones a cinquante-deux ans et deux enfants. Après le décès de Mark Darcy, avec qui elle a vécu dix ans de bonheur, elle est à nouveau en quête de l'homme idéal. Mais ce n'est pas si facile de se remettre sur le marché du célibat. Les mésaventures de Bridget n'ont rien perdu de leur piquant...", "2025", "2:05:00", "https://media.senscritique.com/media/000022514268/300/bridget_jones_folle_de_lui.png", "https://youtu.be/8VIvXqW9_z4", "Renée Zellweger, Colin Firth, Chiwetel Ejiofor, Leo Woodall, Hugh Grant, Emma Thompson", "Mickael Morris"),
  ("Dis-moi juste que tu m'aimes", "Julien et Marie forment une famille heureuse et un couple solide, jusqu’au jour où Anaëlle, l’ex de Julien, reprend contact avec lui. Aveuglée par la jalousie, Marie entame alors, par dépit, une liaison Avec Thomas, son nouveau patron. Elle se retrouve vite embarquée dans une spirale dangereuse qui va mettre en péril bien plus que son mariage...", "2025", "1:51:00", "https://media.senscritique.com/media/000022560980/300/dis_moi_juste_que_tu_maimes.png", "https://youtu.be/TvQFpb8aR_g", "Omar Sy, Élodie Bouchez, José Garcia, Vanessa Paradis, Jennifer Decker, Marie Ayissi", "Anne Le Ny"),
  ("Mercato", "Mercato nous plonge dans les coulisses du football d’aujourd’hui, industrie planétaire où les intérêts se chiffrent en milliards. Driss, agent de joueurs, a sept jours pour sauver sa peau avant la fin du mercato...", "2025", "1:59:00", "https://media.senscritique.com/media/000022592994/300/mercato.jpg", "https://youtu.be/zW7gri3s1_g", "Jamel Debbouze, Monia Chokri, Milo Machado Graner, Hakim Jemili, Vincent Rottiers, Stéphane Bak", "Tristan Séguéla"),
  ("L'attachement", "Sandra, quinquagénaire farouchement indépendante, partage soudainement et malgré elle l’intimité de son voisin de palier et de ses deux enfants. Contre toute attente, elle s’attache peu à peu à cette famille d’adoption....", "2025", "1:46:00", "https://media.senscritique.com/media/000022584014/300/l_attachement.jpg", "https://youtu.be/jafK7yg0whg", "Valéria Bruni-Tedeschi, Pio Marmaï, Vimala Pons, Raphaël Quenard, César Botti, Catherine Mouchet", "Carine Tardieu"),
  ("The Monkey", "Lorsque Bill et Hal, des jumeaux, trouvent dans le grenier un vieux jouet ayant appartenu à leur père, une série de morts atroces commence à se produire autour d'eux...", "2025", "1:38:00", "https://media.senscritique.com/media/000022466997/300/the_monkey.png", "https://youtu.be/bYcBFKwupwY", "Theo James, Tatiana Maslany, Christian Convery, Colin O'Brien, Elijah Wood, Rohan Campbell", "Oz Perkins"),
  ("Peter Pan's Neverland Nightmare", "Adaptation horrifique de l'oeuvre de James Matthew Barrie...", "2025", "1:30:00", "https://media.senscritique.com/media/000022513281/300/peter_pan_s_neverland_nightmare.jpg", "https://youtu.be/OYbxAYK8hoQ", "Charity Kase, Martin Portlock, Kit Green, Megan Placito, Olumide Olorunfemi, Philip Philmar", "Scott Chambers"),
  ("In the Lost Land", "Une reine cherche désespérément à concrétiser son amour. Elle engage alors une puissante sorcière nommée Gray Alys et l’envoie dans le désert fantomatique des Lost Lands, où Alys et son guide, le vagabond Boyce, doivent surpasser l’Homme et le démon...", "2025", "1:41:00", "https://media.senscritique.com/media/000022586849/300/in_the_lost_lands.jpg", "https://youtu.be/hnPsOnw9-JU", "Milla Jovovich, Dave Bautista, Arly Jover, Amara Okereke, Fraser James, Simon Lööf", "Paul W. S. Anderson");


insert into genre (name)
VALUES
("Action"), ("Horreur"), ("Science-fiction"), ("Drame"), ("Romance"), ("Comédie"), ("Aventure"), ("Jeunesse"), ("Thriller"), ("Policier"), ("Criminel"), ("Fantastique"), ("Comédie musical"), ("Film d'animation"), ("Guerre"), ("Thriller érotique"), ("Prison"), ("Western");


insert into movie_genre (movie_id, genre_id)
VALUES
(1, 3),
(1, 1),
(2, 3),
(2, 9),
(3, 4),
(3, 11),
(4, 9),
(4, 10),
(4,17),
(4, 4),
(5, 1),
(5, 11),
(6, 9),
(7, 4),
(8, 3),
(9, 4),
(9, 18),
(10, 7),
(10, 4),
(10, 3),
(11, 4),
(12, 4),
(12, 5),
(13, 9),
(14, 4),
(15, 1),
(15, 3),
(15, 9),
(16, 7),
(16, 6),
(16, 8),
(16, 14),
(17, 6),
(17, 4),
(18, 9),
(18, 1),
(18, 10),
(19, 14),
(20, 4),
(21, 2),
(21, 9),
(21, 4),
(22, 16),
(23, 4),
(23, 9),
(24, 1),
(25, 6),
(25, 1),
(26, 2),
(27, 13),
(28, 4),
(29, 9),
(30, 2),
(30, 6),
(31, 3),
(32, 4),
(33, 2),
(33, 9),
(34, 4),
(34, 17),
(35, 6),
(35, 8),
(36, 9),
(36, 4),
(37, 7),
(37, 6),
(37, 8),
(37, 14),
(38, 4),
(39, 13),
(39, 4),
(40, 10),
(40, 4),
(40, 9),
(41, 4),
(42, 15),
(42, 4),
(43, 1),
(43, 3),
(44, 6),
(44, 5),
(45, 4),
(46, 9),
(46, 6),
(46, 4),
(47, 4),
(48, 2),
(48, 6),
(49, 2),
(49, 7),
(49, 9),
(49, 12),
(50, 12);